/* SELECT * FROM  WHERE */

CREATE DATABASE SWANHUB;

CREATE TABLE USERS(
	UserID BIGINT() PRIMARY KEY;
	Email CHAR(100);
	Username CHAR(50);
	Password CHAR(50);
	Admin BOOLEAN;
	)
	
CREATE TABLE USER_PROFILE(
	UserID BIGINT() FOREIGN KEY PRIMARY KEY;
	First_Name CHAR(100);
	Last_Name CHAR(100);
	DOB DATE();
	CourseID BIGINT() FOREIGN KEY;
	StudentID CHAR(10);
	About MEDIUMTEXT;
	Profile_Picture MEDIUMTEXT;
	)

	
CREATE TABLE COMMENTS(
	CommentID BIGINT() PRIMARY KEY;
	CommentText MEDIUMTEXT;
	DateTimeCommented DATETIME;
	PostID BIGINT() FOREIGN KEY;
	UserID BIGINT() FOREIGN KEY;
	)

CREATE TABLE COURSES(
	CourseID BIGINT() PRIMARY KEY;
	CourseName CHAR(60);
	CourseInfo MEDIUMTEXT;
	)

CREATE TABLE EVENTS(
	EventID BIGINT() PRIMARY KEY;
	EventName CHAR(60);
	EventDescription MEDIUMTEXT;
	StartDate DATE();
	StartTime TIME();
	EndDate DATE();
	EndTime TIME();
	UserID BIGINT() FOREIGN KEY;
	)

CREATE TABLE FRIENDS(
	FriendID BIGINT() PRIMARY KEY;
	StartDate DATETIME();
	UserID BIGINT() FOREIGN KEY;
	)

CREATE TABLE LIKES(
	UserID BIGINT() PRIMARY KEY FOREIGN KEY;
	DateLiked DATETIME();
	PostID BIGINT() FOREIGN KEY;
	)

CREATE TABLE MESSAGES(
	DateTimeOfMessage DATETIME();
	Content LONGTEXT;
	ConversationID BIGINT() PRIMARY KEY FOREIGN KEY;
	)

CREATE TABLE CONVERSATIONS(
	ConversationID BIGINT() PRIMARY KEY;
	UserID BIGINT() FOREIGN KEY;
	FriendID BIGINT() FOREIGN KEY;
	)

CREATE TABLE MEDIA(
	MediaID BIGINT() PRIMARY KEY;
	UserID BIGINT() FOREIGN KEY;
	PostID BIGINT() FOREIGN KEY;
	MediaInfo() MEDIUMTEXT;
	)

CREATE TABLE POSTS(
	PostID BIGINT() PRIMARY KEY;
	Description LONGTEXT;
	Title CHAR(100);
	DatePosted DATETIME;
	UserID BIGINT() FOREIGN KEY;
	)

CREATE TABLE SOCIETIES(
	SocietyID BIGINT() PRIMARY KEY;
	SocietyName CHAR(60);
	SocietyInfo MEDIUMTEXT;
	UserID BIGINT() FOREIGN KEY;
	)
