CREATE DATABASE SWANHUB;

CREATE TABLE USERS(
	UserID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	Email VARCHAR(100) NOT NULL,
	Username VARCHAR(50) NOT NULL,
	UserPassword VARCHAR(50) NOT NULL,
	IsAdmin VARCHAR(1) NOT NULL,
	UNIQUE (Email,Username)
	);
	
CREATE TABLE USER_PROFILE(
	UserID INT(11) PRIMARY KEY NOT NULL,
	First_Name VARCHAR(100) NOT NULL,
	Last_Name VARCHAR(100) NOT NULL,
	DOB DATE NOT NULL,
	CourseID INT(11) NOT NULL,
	StudentID VARCHAR(11) NOT NULL,
	About VARCHAR(1000),
	Profile_Picture VARCHAR(100),
	CONSTRAINT FK_UserCourses FOREIGN KEY (CourseID)
	REFERENCES COURSES(CourseID),
	CONSTRAINT FK_UserProfileLink FOREIGN KEY (UserID)
	REFERENCES USERS(UserID),
	CONSTRAINT Uq_SID 
	UNIQUE (StudentID)
	);

CREATE TABLE COMMENTS(
	CommentID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	CommentText VARCHAR(2000) NOT NULL,
	DateTimeCommented TIMESTAMP NOT NULL,
	PostID INT(11) NOT NULL,
	UserID INT(11) NOT NULL,
	CONSTRAINT FK_PostCommentID FOREIGN KEY (PostID)
	REFERENCES POSTS(PostID),
	CONSTRAINT FK_UserCommentID FOREIGN KEY (UserID)
	REFERENCES USERS(UserID)
	);

CREATE TABLE COURSES(
	CourseID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	CourseName VARCHAR(60) NOT NULL,
	CourseInfo VARCHAR(1000),
	UNIQUE (CourseName)
	);

CREATE TABLE EVENTS(
	EventID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	EventName VARCHAR(60) NOT NULL,
	EventDescription VARCHAR(1000),
	StartTime DATETIME,
	EndTime DATETIME,
	UserID INT(11) NOT NULL,
	CONSTRAINT FK_Event FOREIGN KEY (UserID)
	REFERENCES USERS(UserID),
	CONSTRAINT Uq_EventName
	UNIQUE (EventName)
	);

CREATE TABLE FRIENDS(
	FriendID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	StartDate TIMESTAMP NOT NULL,
	UserID INT(11) NOT NULL,
	CONSTRAINT FK_Friend FOREIGN KEY (UserID)
	REFERENCES USERS(UserID)
	);

CREATE TABLE LIKES(
	UserID INT(11) PRIMARY KEY NOT NULL,
	DateLiked TIMESTAMP NOT NULL,
	PostID INT(11) NOT NULL,
	CONSTRAINT FK_Like FOREIGN KEY (UserID)
	REFERENCES USERS(UserID),
	CONSTRAINT FK_PostLike FOREIGN KEY (PostID)
	REFERENCES POSTS(PostID)
	);

CREATE TABLE MESSAGES(
	MessageID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	DateTimeOfMessage TIMESTAMP NOT NULL,
	Content VARCHAR(2000) NOT NULL,
	ConversationID INT(11) NOT NULL,
	CONSTRAINT FK_Conversation FOREIGN KEY (ConversationID)
	REFERENCES CONVERSATIONS(ConversationID)
	);

CREATE TABLE CONVERSATIONS(
	ConversationID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	UserID INT(11) NOT NULL,
	FriendID INT(11) NOT NULL,
	CONSTRAINT FK_UserConversations FOREIGN KEY (UserID)
	REFERENCES USERS(UserID),
	CONSTRAINT FK_FriendConversations FOREIGN KEY (FriendID)
	REFERENCES FRIENDS(FriendID)
	);

CREATE TABLE MEDIA(
	MediaID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	UserID INT(11) NOT NULL,
	PostID INT(11) NOT NULL,
	MediaInfo VARCHAR(300),
	CONSTRAINT FK_UserMedia FOREIGN KEY (UserID)
	REFERENCES USERS(UserID),
	CONSTRAINT FK_PostMedia FOREIGN KEY (PostID)
	REFERENCES POSTS(PostID)
	);

CREATE TABLE POSTS(
	PostID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	Body VARCHAR(2000) NOT NULL,
	Title VARCHAR(100) NOT NULL,
	DatePosted DATETIME NOT NULL,
	UserID INT(11) NOT NULL,
	CONSTRAINT FK_UserPost FOREIGN KEY (UserID)
	REFERENCES USERS(UserID)
	);

CREATE TABLE SOCIETIES(
	SocietyID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	SocietyName VARCHAR(60) NOT NULL,
	SocietyInfo VARCHAR(1000),
	UserID INT(11),
	CONSTRAINT FK_UserSociety FOREIGN KEY (UserID)
	REFERENCES USERS(UserID),
	CONSTRAINT Uq_SocietyName
	UNIQUE (SocietyName)
	);


ALTER TABLE COMMENTS AUTO_INCREMENT=1000;

ALTER TABLE COURSES AUTO_INCREMENT=1000;

ALTER TABLE EVENTS AUTO_INCREMENT=1000;

ALTER TABLE FRIENDS AUTO_INCREMENT=1000;

ALTER TABLE MESSAGES AUTO_INCREMENT=1000;

ALTER TABLE CONVERSATIONS AUTO_INCREMENT=1000;

ALTER TABLE MEDIA AUTO_INCREMENT=1000;

ALTER TABLE POSTS AUTO_INCREMENT=1000;

ALTER TABLE SOCIETIES AUTO_INCREMENT=1000;
